### ISSUE TITLE
Accept undefined filters for useLiveQuery in ModelDB hooks

### ISSUE THREAD

**Issue by raykyri** [canvasxyz/canvas#191]
![image](https://github.com/canvasxyz/canvas/assets/1273926/719e5dfc-a4ab-4a18-b64b-f0e1499850e2)

Doing this much chaining seems bad, but there will probably be cases where filters are not always populated upon initialization and their types are undefined

**Comment by rjwebb** [comment]
How would we want the filter to behave in this situation? JavaScript often has a convention of treating fields on objects where the value is undefined as being absent (e.g. when passing in option objects or function parameters), but it could also literally mean "return objects where this field === undefined".

If the wallet doesn't exist, then I would expect any queries that are looking up information associated with it to also not return anything. So naively you could imagine only calling `useLiveQuery` if the wallet !== undefined, but React requires the set of hooks used within a component to not change over its lifecycle. Maybe we need a way of constructing an "empty" query in useLiveQuery, so we could write something like (where if the query field is undefined, it doesn't return anything? still feels like a footgun, or maybe `{}` should mean select nothing): 
```
const registration1 = useLiveQuery(app, "encryptionKeys", wallet && { where: { address: wallet.address } } )
```

**Comment by raykyri** [comment]
Given that dag-cbor doesn't encode undefined, we should probably err on the side of assuming values can't be undefined in the database in which case `where: { address: undefined }` would work identically to `where: {}`. 

I think `where: {}` should be treated as select everything, so filters are only applied if they are explicitly defined, but `where: {}` doesn't literally mean "select only records with no subfields" because that wouldn't be very useful.
