### ISSUE TITLE
Add single-page cheat sheet doc for the API

### ISSUE THREAD

**Issue by raykyri** [canvasxyz/canvas#202]
This could be the first item under the API sidebar, above all the individual NPM package docs, called "API Reference", "API Summary", "Cheat Sheet", or similar.

**Comment by rjwebb** [comment]
I feel like an "API Reference" and a "Cheat Sheet" achieve different things, I would expect an API Reference to be totally comprehensive and include the doc strings and examples for every exposed function (hopefully automatically generated from the code e.g. using typedoc or tsdoc), while a Cheat Sheet would be as concise as possible and probably not explain what all of the functions do (but ideally have links to the API reference).
