### ISSUE TITLE
Allow apps to check if the session signer has a cached session for a given topic and address

### ISSUE THREAD

**Issue by rjwebb** [canvasxyz/canvas#256]
Currently, if we want to check if a valid session exists for a given topic and address (wallet address), there are two hacky approaches:
- call `getSession` with `options.fromCache = true`. This can work but it assumes that the address we are trying to sign for is the same one that would be returned by `signer.getAddress()`. This might not be true if the user has changed the active address in their crypto wallet extension / client.
- call the sign function on a `Message<Session|Action>` where `message.payload.address` = the wallet address. If it signs the message then we know that a session exists. This would require us to construct some kind of dummy object just so that we can implicitly pass in the address value we are interested in.

We already have a function on `AbstractSessionSigner` called `getCachedSession` that returns a session for a given topic and address. It's currently `protected`, would be OK if we made it `public`? Also worth considering is if we could provide a synchronous method that lets us cheaply check whether a cached session exists. I know that `localStorage` is actually a synchronous API, so this would work but depending on how we store sessions we might not always be able to guarantee this.

**Comment by raykyri** [comment]
Completed in f2eabbabd.
