### ISSUE TITLE
GossiplogService Sync Error When Syncing Large Batch of Missed Entries

### ISSUE THREAD

**Issue by Chandelier-02** [canvasxyz/canvas#295]
I have been stress testing the GossiplogService to see if it would suit my projects needs. So far, it has proved to be very reliable and fast. However, there are two use cases I have noticed that it seems to not be able to handle: (For these use cases, there are two nodes communicating with one-another)

1. The nodes are connected, but one node creates thousands of entries at once. Think a Promise.all on a couple thousand append operations. I am aware this would be a very abnormal use case, but its connected to the one below due to having the same errors.
2. The nodes are disconnected and one node creates thousands of entries > 10_000, and then they re-connect.

Most of the errors I get are from Libp2p stating that there are socket errors on the tcp connection, the tcp connection getting destroyed, and gossipsub truncation of messages. I have noticed that if I wait long enough after these errors have passed, the sync continues and works once again. However, if there are sufficient enough entries, think > 10_000, these issues come up again, the sync recovers, then eventually the sync reaches its max retries and doesn't try to send anything anymore and nothing gets synced. 

This is the max retries error I get before everything stops working: 
canvas:gossiplog:[test.gossiplog]:sync:error sync failed: 'exceeded sync retry limit:

For the 1st case, I have noticed that adding a delay of 10ms between append operations alleviates the problem. My main worry, however, is with the 2nd use case. If a node goes offline for an extended period of time, and then comes back online, it may never properly sync due to the errors mentioned above. 

From these issues, I think that the sync may be overloading the TCP connections? Then, some messages time out in the Sync service, causing a retry. Maybe some form of back-pressure in the sync could help with this?

Any thoughts on this issue? Am I using the log in a way its not meant to be used?

**Comment by raykyri** [comment]
The way that Merkle sync works for large numbers of actions is still unoptimized, and getting everything to consistently converge still requires manual work for syncing any meaningful number of messages or connections. This is mostly because read/write locking is tricky on certain environments, so we can't just hold a single sync transaction open forever (or it might lock out everyone else).

By default, we timeout the sync after 3 seconds and then resume syncing the next time a regularly scheduled sync occurs, which should be within a few seconds. I don't recall how rescheduling syncs after the "initial sync" works off the top of my head, but new syncs should be scheduled quickly if an existing sync hasn't completed (which is the behavior you're seeing where sync pauses and continues).

If there are libp2p errors that's unexpected and complicates things. It might be something related to your setup, so details on your libp2p config would be useful (also: are you syncing server-to-server or browser-to server, which Canvas version are you using, do you have a Github repo with the test you're running).

**Comment by Chandelier-02** [comment]
Okay, so I split each GossipLog into its own process and ran it. That alleviated the issue to some degree, but it is still there, just needs more entries being sent at the same time to cause the errors. 

Here is the github repo that I am running these tests in:
https://github.com/Chandelier-02/GossipLog-Stress-Tests

You'll see the truncated log files in test/logs/catch-up-entries-test/

The Libp2p config is in the src/gossiplog-process.ts file.

The test file details the amount of entries that I am creating and attempting to sync.

**Comment by Chandelier-02** [comment]
So, I have been testing the GossipLog once again now that I have seen some substantial changes to it. I am still having an issue when syncing a large number of entries (50,000) between two peers. 

Here is the process:
1. Create a new gossiplog service and append 50,000 messages to the log
2. Create another gossiplog service and wait for a 'sync' event

When I am going through the debug logs, I am noticing that the sync works perfectly fine for entries with clock values 0-255, but then it randomly gets an entry with a clock value of 16,384 and tries to insert it, leading to an error being thrown. This happens every time I run this test and with the same clock values. Given the clock values are 255 and 16384, I would assume this may have something to do with the id generation or varint stuff. 

Here are some of the error messages I have been seeing:
`
Received message containing clock value: 254
2024-06-24T20:34:16.941Z canvas:gossiplog:[test-topic] inserting message g5vvqfknpge975iej5um5oa5d131sq7l
2024-06-24T20:34:16.943Z canvas:gossiplog:[test-topic] applying g5vvqfknpge975iej5um5oa5d131sq7l {
  topic: 'test-topic',
  clock: 255,
  parents: [ 'g5v9jn1ngf01pqttt81n21fc4l3ugfug' ],
  payload: { id: '44ef396d-d192-4f52-98df-0807a4732f00' }
}
Received message containing clock value: 255
2024-06-24T20:34:16.951Z canvas:gossiplog:[test-topic] inserting message g60015lv53bdi5o4v1cht338t79g19at
2024-06-24T20:34:16.953Z canvas:gossiplog:[test-topic]:error missing parent vtvmslpn672g6ll72mpldmhhcuhsp9i1 of message g60015lv53bdi5o4v1cht338t79g19at: {
  topic: 'test-topic',
  clock: 16384,
  parents: [ 'vtvmslpn672g6ll72mpldmhhcuhsp9i1' ],
  payload: { id: 'c249ecd2-ffb1-45c7-8fa3-63cf81c145f5' }
}
2024-06-24T20:34:16.953Z canvas:gossiplog:[test-topic]:service closed outgoing stream 8 to peer 12D3KooWFfGeuqRSbbYUv6bbJCdQ9GzmG1FNAHDyz2c2mmUi8LCL
2024-06-24T20:34:16.953Z canvas:gossiplog:[test-topic]:service:error failed to sync with peer: Error: missing parent vtvmslpn672g6ll72mpldmhhcuhsp9i1 of message g60015lv53bdi5o4v1cht338t79g19at
    at file:///home/chandler-dykes/Ryzyliant/GossipLogTests/node_modules/.pnpm/@canvas-js+gossiplog@0.10.0-beta.4_patch_hash=oalavf2x3w6mjcnzz7tqlmvhcm_@chainsafe+libp2p-gossipsub@13.0.0_react@18.2.0/node_modules/@canvas-js/gossiplog/lib/AbstractGossipLog.js:148:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/chandler-dykes/Ryzyliant/GossipLogTests/node_modules/.pnpm/@canvas-js+okra-lmdb@0.1.2/node_modules/@canvas-js/okra-lmdb/lib/Tree.js:90:26
    at async file:///home/chandler-dykes/Ryzyliant/GossipLogTests/node_modules/.pnpm/p-queue@8.0.1/node_modules/p-queue/dist/index.js:187:36
2024-06-24T20:34:16.953Z canvas:gossiplog:[test-topic]:service waiting 962ms before trying again (1/5)
`

**Comment by Chandelier-02** [comment]
Not very sure if this will add any more context, but when I have two nodes actively syncing as entries are being appended to one node, I do not see this issue. The issue seems to show up only when a new node with 0 entries joins and is over 16384 entries behind another node.

**Comment by joeltg** [comment]
Looks like this has been addressed by the combination of the GossipLog Id changes in #308 and the non-blocking sync refactor. If run into other problems please open more issues, these have been really helpful!
