### ISSUE TITLE
Race condition when multiple db.merge() calls are made without async

### ISSUE THREAD

**Issue by raykyri** [canvasxyz/canvas#364]
db.get() and db.merge() both depend on an async getModelValue() call outside the Function/ContractRuntime. This means that if you remove the `await`s inside `app.actions.updateGameMultipleMerges` in packages/core/test/canvas.ts, the the reads in each call to db.merge() will now read from the initial state of the database.

This only happens with db.merge() operations, because we cache db.set() writes in `context.modelEntries[model][key]` to make it effectively synchronous.

We could fix this by adding a lock inside the model API, so db.merge() waits for any other pending db.merge() operations to finish.

**Comment by rjwebb** [comment]
The "effects" would be subtly different from the `Effect` type we are currently using, because they would also include `merge` and `update` effects which could then be replaced with "set" operations when the action is complete.

**Comment by raykyri** [comment]
Fixed by locking.
