### ISSUE TITLE
Migration to poll.fil.org means confusing login failure at metropolis.vote

### ISSUE THREAD

**Issue by patcon** [canvasxyz/canvas#368]
Hey @rjwebb @raykyri -- was just exploring the state of the project as I'm working on experimenting with changes to the Polis UI, and notice that GitHub login is no longer working on metropolis.vote 

https://github.com/user-attachments/assets/7d01e8e9-968c-40e4-9265-b06ddc0264db

Realized afterward that this is because you've migrated to using poll.fil.org

Confusingly, when I was previously logged in on my phone (before the switch of the GitHub `redirect_uri`), that means my phone works fine. Presumably you might have users of metropolis.vote who won't run into an issue until their session expires.

Just giving you heads up in case this is an important failure of a user flow (no explanation and confusing error for ppl using the old site)

Hope you're both well!

**Comment by rjwebb** [comment]
Nice to hear from you as always :D

Thanks for pointing this out, I think we need to update the domain records to redirect the user from metropolis.vote -> poll.fil.org

**Comment by patcon** [comment]
Aw hey Bob :)

I see from you nameservers that you're using cloudflare, so it's just this: (to save you the bother of looking it up)

<img width="1216" alt="Screenshot 2024-10-15 at 12 30 29 PM" src="https://github.com/user-attachments/assets/435bf6fa-713b-466a-a108-834e79ca90fd">

(10 free redirects/domain with free plan, so shouldn't need any special plan)
Docs: https://developers.cloudflare.com/fundamentals/setup/manage-domains/redirect-domain/

**Comment by raykyri** [comment]
Oh nice! This is much easier than making the change on the backend.

**Comment by patcon** [comment]
heh and sorry, just realized i ninja-posted this in wrong repo last week 😄

**Comment by raykyri** [comment]
Cloudflare redirect rules didn't work so we had to change our DNS for this to work. But this is fixed now.
